version: "3.9"

services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: "kafka:9092"
    depends_on:
      - kafka

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      ALLOW_PLAINTEXT_LISTENER: "yes"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: yakov
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  publish_podcasts:
    build:
      context: .
      dockerfile: publish_podcasts/Dockerfile
    container_name: publish_podcasts
    environment:
      KAFKA_BROKER: kafka:9092
      FILE_PATH: app/podcasts
    ports:
      - "8001:8001"
    volumes:
      - ./C:/podcasts:/app/podcasts
    depends_on:
      - kafka


  processing:
    build:
      context: .
      dockerfile: processing/Dockerfile
    container_name: processing
    environment:
      KAFKA_BROKER: kafka:9092
      MONGODB_USER: admin
      MONGODB_PASSWORD: yakov
      MONGODB_DATABASE: the_muezzin
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_AUTH_DB: admin
    ports:
      - "8003:8003"



volumes:
  mongo_data: